# Generated by Django 2.2.2 on 2020-11-25 06:17

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_uz', models.CharField(max_length=100, null=True)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('body_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('body_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('body_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=news.models.upload_location)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date_published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('slider', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('status', models.BooleanField(verbose_name='slider')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
