# Generated by Django 2.2.2 on 2020-11-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201125_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ungnewsmodel',
            name='slider',
        ),
    ]
