# Generated by Django 2.2.2 on 2020-12-01 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_ungnewsmodel_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ungnewsmodel',
            name='author',
        ),
    ]
