# Generated by Django 2.2.2 on 2020-12-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_ungnewsmodel_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ungnewsmodel',
            old_name='status',
            new_name='slider_status',
        ),
    ]
