# Generated by Django 2.2.2 on 2020-12-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20201207_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ungnewsmodel',
            old_name='slider_status',
            new_name='status',
        ),
    ]
