# Generated by Django 2.2.2 on 2021-01-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20210106_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='ungnewsmodel',
            name='youth_stat',
            field=models.BooleanField(default=1, verbose_name='youth_union'),
            preserve_default=False,
        ),
    ]
