# Generated by Django 2.2.2 on 2021-01-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_ungnewsmodel_youth_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ungnewsmodel',
            name='date_published',
            field=models.DateTimeField(verbose_name='date_published'),
        ),
    ]
