# Generated by Django 2.2.2 on 2021-01-14 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20210114_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ungnewsmodel',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 14, 10, 14, 11, 74431), verbose_name='date_published'),
        ),
    ]
