# Generated by Django 2.2.2 on 2021-01-15 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20210115_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ungnewsmodel',
            options={'verbose_name': 'Yangiliklar', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterField(
            model_name='ungnewsmodel',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 16, 33, 40, 15287), verbose_name='date_published'),
        ),
    ]
