# Generated by Django 2.2.2 on 2021-01-15 11:45

import datetime
from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20210115_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to=news.models.upload_location)),
                ('text', models.TextField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Reyting ikonka',
                'verbose_name_plural': 'Reyting ikonkalar',
            },
        ),
        migrations.AlterField(
            model_name='ungnewsmodel',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 15, 16, 45, 39, 613267), verbose_name='date_published'),
        ),
    ]
