# Generated by Django 2.2.2 on 2021-01-20 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20210120_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ungnewsmodel',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 9, 52, 45, 515277), verbose_name='date_published'),
        ),
    ]
