# Generated by Django 2.2.2 on 2021-01-20 06:14

import datetime
from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20210120_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ungnewsmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='ungnewsmodel',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.upload_location),
        ),
        migrations.AddField(
            model_name='ungnewsmodel',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.upload_location),
        ),
        migrations.AddField(
            model_name='ungnewsmodel',
            name='image_uz',
            field=models.ImageField(blank=True, null=True, upload_to=news.models.upload_location),
        ),
        migrations.AlterField(
            model_name='ungnewsmodel',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 11, 14, 8, 779370), verbose_name='date_published'),
        ),
    ]
