# Generated by Django 2.2.2 on 2021-01-27 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_auto_20210120_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ungnewsmodel',
            options={'ordering': ['-date_published']},
        ),
        migrations.AlterField(
            model_name='ungnewsmodel',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 10, 4, 51, 73320), verbose_name='date_published'),
        ),
    ]
