# Generated by Django 2.2.2 on 2021-06-01 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_auto_20210120_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ungnewsmodel',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 12, 3, 5, 890793), verbose_name='date_published'),
        ),
    ]
