# Generated by Django 2.2.2 on 2021-06-02 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20210601_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ungnewsmodel',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 18, 13, 27, 895697), verbose_name='date_published'),
        ),
    ]
