# Generated by Django 2.2.2 on 2021-03-02 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20210127_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='ungnewsmodel',
            name='mumkin_status',
            field=models.BooleanField(default=True, verbose_name='mumkin'),
        ),
        migrations.AlterField(
            model_name='ungnewsmodel',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 15, 33, 20, 444198), verbose_name='date_published'),
        ),
    ]
