# Generated by Django 2.2.2 on 2021-06-17 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0024_auto_20210607_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ungnewsmodel',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 11, 6, 42, 901326), verbose_name='date_published'),
        ),
    ]
