# Generated by Django 2.2.2 on 2021-06-17 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_auto_20210617_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ungnewsmodel',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 17, 31, 48, 826609), verbose_name='date_published'),
        ),
    ]
