# Generated by Django 2.2.2 on 2021-06-29 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0030_auto_20210629_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ungnewsmodel',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 14, 46, 47, 26167), verbose_name='date_published'),
        ),
    ]
