# Generated by Django 2.2.2 on 2021-08-09 12:45

import ckeditor.fields
import datetime
from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0034_auto_20210701_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplNewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.TextField(blank=True, null=True)),
                ('news_body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=news.models.upload_location)),
                ('date_published', models.DateTimeField(default=datetime.datetime(2021, 8, 9, 17, 45, 17, 640327), verbose_name='date_published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Compliance Yangiliklar',
                'verbose_name_plural': 'Compliance Yangiliklar',
            },
        ),
        migrations.AlterField(
            model_name='ungnewsmodel',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 17, 45, 17, 640327), verbose_name='date_published'),
        ),
    ]
