# Generated by Django 2.2.2 on 2021-08-09 12:50

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0035_auto_20210809_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='complnewsmodel',
            name='news_body_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complnewsmodel',
            name='news_body_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complnewsmodel',
            name='news_body_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complnewsmodel',
            name='news_title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complnewsmodel',
            name='news_title_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complnewsmodel',
            name='news_title_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complnewsmodel',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 17, 50, 31, 193608), verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='ungnewsmodel',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 17, 50, 31, 193608), verbose_name='date_published'),
        ),
    ]
