# Generated by Django 2.2.2 on 2021-06-17 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 17, 17, 31, 48, 829609), verbose_name='date_published'),
        ),
        migrations.AddField(
            model_name='applicationform',
            name='status',
            field=models.BooleanField(default=False, verbose_name="o'qilgan"),
        ),
    ]
