# Generated by Django 2.2.2 on 2021-06-22 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0002_auto_20210617_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('date_subscribed', models.DateTimeField(default=datetime.datetime(2021, 6, 22, 18, 17, 32, 707267), verbose_name='date_subscribed')),
            ],
            options={
                'ordering': ('-date_subscribed',),
            },
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 18, 17, 32, 707267), verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='status',
            field=models.BooleanField(default=False, verbose_name="O'qilgan"),
        ),
    ]
