# Generated by Django 2.2.2 on 2021-06-28 06:19

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0003_auto_20210622_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionaireModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('votes_count', models.IntegerField(blank=True, default=0, null=True)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2021, 6, 28, 11, 19, 0, 412082), verbose_name='date_created')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 11, 19, 0, 411087), verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='mailsmodel',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 11, 19, 0, 411087), verbose_name='date_subscribed'),
        ),
    ]
