# Generated by Django 2.2.2 on 2021-06-28 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0004_auto_20210628_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionairemodel',
            name='email',
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 11, 20, 8, 632395), verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='mailsmodel',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 11, 20, 8, 632395), verbose_name='date_subscribed'),
        ),
        migrations.AlterField(
            model_name='questionairemodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 11, 20, 8, 632395), verbose_name='date_created'),
        ),
    ]
