# Generated by Django 2.2.2 on 2021-06-29 09:45

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0005_auto_20210628_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 14, 45, 12, 923142), verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='mailsmodel',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 14, 45, 12, 923142), verbose_name='date_subscribed'),
        ),
        migrations.AlterField(
            model_name='questionairemodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 14, 45, 12, 923142), verbose_name='date_created'),
        ),
        migrations.CreateModel(
            name='OptionsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive.QuestionaireModel')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
