# Generated by Django 2.2.2 on 2021-06-29 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0006_auto_20210629_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 14, 46, 47, 29168), verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='mailsmodel',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 14, 46, 47, 29168), verbose_name='date_subscribed'),
        ),
        migrations.AlterField(
            model_name='questionairemodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 29, 14, 46, 47, 29168), verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='questionairemodel',
            name='full_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
