# Generated by Django 2.2.2 on 2021-07-01 12:16

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0007_auto_20210629_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optionsmodel',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='optionsmodel',
            name='option_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optionsmodel',
            name='option_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optionsmodel',
            name='option_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionairemodel',
            name='full_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionairemodel',
            name='full_text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionairemodel',
            name='full_text_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 17, 16, 57, 867568), verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='mailsmodel',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 17, 16, 57, 868568), verbose_name='date_subscribed'),
        ),
        migrations.AlterField(
            model_name='optionsmodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='interactive.QuestionaireModel'),
        ),
        migrations.AlterField(
            model_name='questionairemodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 17, 16, 57, 868568), verbose_name='date_created'),
        ),
    ]
