# Generated by Django 2.2.2 on 2021-08-09 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0011_auto_20210809_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationform',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 17, 50, 31, 196608), verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='mailsmodel',
            name='date_subscribed',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 17, 50, 31, 196608), verbose_name='date_subscribed'),
        ),
        migrations.AlterField(
            model_name='questionairemodel',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 17, 50, 31, 197608), verbose_name='date_created'),
        ),
    ]
