# Generated by Django 2.2.2 on 2020-12-07 06:16

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import tenders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('name_uz', models.CharField(blank=True, max_length=50, null=True)),
                ('inn', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('address_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('address_en', models.CharField(blank=True, max_length=50, null=True)),
                ('address_uz', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('clientBillNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('deliveryTerms', models.CharField(blank=True, max_length=50, null=True)),
                ('deliveryTerms_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('deliveryTerms_en', models.CharField(blank=True, max_length=50, null=True)),
                ('deliveryTerms_uz', models.CharField(blank=True, max_length=50, null=True)),
                ('deadline', models.CharField(blank=True, max_length=50, null=True)),
                ('deadline_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('deadline_en', models.CharField(blank=True, max_length=50, null=True)),
                ('deadline_uz', models.CharField(blank=True, max_length=50, null=True)),
                ('paymentTerms', models.CharField(blank=True, max_length=50, null=True)),
                ('paymentTerms_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('paymentTerms_en', models.CharField(blank=True, max_length=50, null=True)),
                ('paymentTerms_uz', models.CharField(blank=True, max_length=50, null=True)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date_published')),
                ('date_ends', models.DateTimeField(auto_now=True, verbose_name='date_ending')),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_uz', models.CharField(max_length=100, null=True)),
                ('asosiy_talablar', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('asosiy_talablar_ru', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('asosiy_talablar_en', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('asosiy_talablar_uz', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('file', models.FileField(upload_to=tenders.models.upload_location)),
                ('date_published', models.DateTimeField(auto_now_add=True, verbose_name='date_published')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date_updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('status', models.BooleanField(default=True, verbose_name='Is Open')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_tenders', to='tenders.CompanyModel')),
            ],
        ),
        migrations.CreateModel(
            name='TenderLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_ru', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_uz', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_uz', models.TextField(null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_ru', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_en', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_uz', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.FloatField(blank=True, max_length=15, null=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.Tender')),
            ],
        ),
    ]
