# Generated by Django 2.2.2 on 2020-12-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderlot',
            name='number',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
