# Generated by Django 2.2.2 on 2020-12-07 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_auto_20201207_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderlot',
            name='number',
        ),
    ]
