# Generated by Django 2.2.2 on 2020-12-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_remove_tenderlot_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderlot',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is Open'),
        ),
    ]
