# Generated by Django 2.2.2 on 2020-12-07 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_tenderlot_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderlot',
            name='status',
        ),
    ]
