# Generated by Django 2.2.2 on 2020-12-09 07:01

import ckeditor.fields
from django.db import migrations, models
import tenders.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0006_companymodel_company_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymodel',
            name='company_slug',
        ),
    ]
