# Generated by Django 2.2.2 on 2020-12-09 07:03

import ckeditor.fields
from django.db import migrations, models
import tenders.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0007_auto_20201209_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileurl', models.FileField(upload_to=tenders.models.location_fo_upload)),
                ('desciption', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
