# Generated by Django 2.2.2 on 2020-12-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0007_remove_companymodel_company_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='company_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
