# Generated by Django 2.2.2 on 2020-12-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0008_filetender'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetender',
            name='filename',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
