# Generated by Django 2.2.2 on 2020-12-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0008_companymodel_company_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymodel',
            name='company_slug',
        ),
    ]
