# Generated by Django 2.2.2 on 2020-12-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0009_filetender_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filetender',
            old_name='desciption',
            new_name='description',
        ),
    ]
