# Generated by Django 2.2.2 on 2020-12-09 08:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0010_auto_20201209_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetender',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filetender',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filetender',
            name='description_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filetender',
            name='filename_en',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='filetender',
            name='filename_ru',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='filetender',
            name='filename_uz',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
