# Generated by Django 2.2.2 on 2020-12-09 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0011_auto_20201209_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='fileInfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='file_info', to='tenders.FileTender'),
            preserve_default=False,
        ),
    ]
