# Generated by Django 2.2.2 on 2020-12-09 09:58

from django.db import migrations, models
import tenders.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0012_tender_fileinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filetender',
            old_name='fileurl',
            new_name='fileurl_en',
        ),
        migrations.AddField(
            model_name='filetender',
            name='fileurl_ru',
            field=models.FileField(default=1, upload_to=tenders.models.location_fo_upload),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filetender',
            name='fileurl_uz',
            field=models.FileField(default=1, upload_to=tenders.models.location_fo_upload),
            preserve_default=False,
        ),
    ]
