# Generated by Django 2.2.2 on 2020-12-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0013_auto_20201209_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='file',
        ),
    ]
