# Generated by Django 2.2.2 on 2020-12-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0014_remove_tender_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderlot',
            name='number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
