# Generated by Django 2.2.2 on 2021-01-07 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0015_tenderlot_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetender',
            name='tender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenders.Tender'),
        ),
    ]
