# Generated by Django 2.2.2 on 2021-01-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0016_filetender_tender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='company',
        ),
    ]
