# Generated by Django 2.2.2 on 2021-01-18 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0021_auto_20210114_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='tender',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 18, 10, 0, 12, 22769), verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='name',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='name_en',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='name_ru',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='name_uz',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
