# Generated by Django 2.2.2 on 2021-01-19 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0024_auto_20210119_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='clientBillNumber',
            field=models.CharField(blank=True, max_length=450, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 9, 39, 18, 459894), verbose_name='date_end'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 9, 39, 18, 459894), verbose_name='date_published'),
        ),
    ]
