# Generated by Django 2.2.2 on 2021-01-19 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0025_auto_20210119_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tender',
            options={'ordering': ['-date_published']},
        ),
        migrations.AlterField(
            model_name='tender',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 11, 7, 47, 691682), verbose_name='date_end'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 11, 7, 47, 691682), verbose_name='date_published'),
        ),
    ]
