# Generated by Django 2.2.2 on 2021-01-20 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0026_auto_20210119_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 9, 52, 45, 518280), verbose_name='date_end'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 9, 52, 45, 518280), verbose_name='date_published'),
        ),
    ]
