# Generated by Django 2.2.2 on 2021-01-27 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0028_auto_20210120_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 10, 10, 55, 415446), verbose_name='date_end'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 10, 10, 55, 415446), verbose_name='date_published'),
        ),
    ]
