# Generated by Django 2.2.2 on 2021-01-27 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0029_auto_20210127_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 14, 44, 8, 246479), verbose_name='date_end'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 27, 14, 44, 8, 246479), verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
