# Generated by Django 2.2.2 on 2021-06-02 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0029_auto_20210601_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 18, 13, 27, 896534), verbose_name='date_end'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 18, 13, 27, 896534), verbose_name='date_published'),
        ),
    ]
