# Generated by Django 2.2.2 on 2021-02-22 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0031_auto_20210222_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 22, 15, 25, 34, 666398), verbose_name='date_end'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 22, 15, 25, 34, 666398), verbose_name='date_published'),
        ),
        migrations.AlterField(
            model_name='tenderlot',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
