# Generated by Django 2.2.2 on 2021-06-22 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0033_auto_20210617_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 18, 17, 32, 707267), verbose_name='date_end'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 18, 17, 32, 707267), verbose_name='date_published'),
        ),
    ]
