# Generated by Django 2.2.2 on 2021-07-01 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0040_auto_20210701_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 17, 23, 51, 240054), verbose_name='date_end'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 1, 17, 23, 51, 240054), verbose_name='date_published'),
        ),
    ]
