# Generated by Django 2.2.2 on 2021-08-09 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0041_auto_20210701_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 17, 45, 17, 654329), verbose_name='date_end'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 17, 45, 17, 654329), verbose_name='date_published'),
        ),
    ]
