# Generated by Django 2.2.2 on 2021-08-09 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0042_auto_20210809_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 17, 50, 31, 195608), verbose_name='date_end'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 9, 17, 50, 31, 195608), verbose_name='date_published'),
        ),
    ]
