# Generated by Django 2.2.2 on 2020-12-14 05:26

from django.db import migrations, models
import django.db.models.deletion
import pagenavbar.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ungfiles', '0002_auto_20201212_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('img', models.ImageField(upload_to=pagenavbar.models.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='MenuSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('menucategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pagenavbar.MenuCategories')),
                ('redir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ungfiles.Category')),
            ],
        ),
    ]
