# Generated by Django 2.2.2 on 2020-12-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagenavbar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategories',
            name='name_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='menucategories',
            name='name_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='menucategories',
            name='name_uz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='menusubcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='menusubcategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='menusubcategory',
            name='name_uz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
