# Generated by Django 2.2.2 on 2020-12-14 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagenavbar', '0002_auto_20201214_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusubcategory',
            name='menucategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='pagenavbar.MenuCategories'),
        ),
    ]
