# Generated by Django 2.2.2 on 2020-12-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagenavbar', '0003_auto_20201214_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menucategories',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='menusubcategory',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
