# Generated by Django 2.2.2 on 2020-12-21 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagenavbar', '0004_auto_20201217_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('url', models.CharField(blank=True, max_length=250, null=True)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_sub_category', to='pagenavbar.MenuSubCategory')),
            ],
        ),
    ]
