# Generated by Django 2.2.2 on 2020-12-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagenavbar', '0005_childsubcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='childsubcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='childsubcategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='childsubcategory',
            name='name_uz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
