# Generated by Django 2.2.2 on 2020-12-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagenavbar', '0006_auto_20201221_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='childsubcategory',
            old_name='subcategory',
            new_name='menusubcategory',
        ),
    ]
