# Generated by Django 2.2.2 on 2020-12-24 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ungfiles', '0006_auto_20201222_1427'),
        ('pagenavbar', '0007_auto_20201221_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategories',
            name='redir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ungfiles.Category'),
        ),
    ]
