# Generated by Django 2.2.2 on 2021-08-24 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadCv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=500, null=True)),
                ('position', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(blank=True, max_length=500, null=True)),
                ('level', models.CharField(blank=True, max_length=500, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.UploadCv')),
            ],
        ),
        migrations.CreateModel(
            name='LanguagesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang_name', models.CharField(blank=True, max_length=500, null=True)),
                ('writing', models.IntegerField(blank=True, null=True)),
                ('reading', models.IntegerField(blank=True, null=True)),
                ('speaking', models.IntegerField(blank=True, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.UploadCv')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraEducationInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=500, null=True)),
                ('speciality', models.CharField(blank=True, max_length=500, null=True)),
                ('date_started', models.CharField(blank=True, max_length=500, null=True)),
                ('date_ended', models.CharField(blank=True, max_length=500, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.UploadCv')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.CharField(blank=True, max_length=500, null=True)),
                ('date_ended', models.CharField(blank=True, max_length=500, null=True)),
                ('company_name', models.CharField(blank=True, max_length=500, null=True)),
                ('position', models.CharField(blank=True, max_length=500, null=True)),
                ('achievements', models.CharField(blank=True, max_length=500, null=True)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('recommendations', models.CharField(blank=True, max_length=500, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.UploadCv')),
            ],
        ),
        migrations.CreateModel(
            name='EducationInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=500, null=True)),
                ('faculty', models.CharField(blank=True, max_length=500, null=True)),
                ('speciality', models.CharField(blank=True, max_length=500, null=True)),
                ('date_started', models.CharField(blank=True, max_length=500, null=True)),
                ('date_ended', models.CharField(blank=True, max_length=500, null=True)),
                ('UploadCv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr.UploadCv')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInformationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_date', models.CharField(blank=True, max_length=500, null=True)),
                ('salary', models.CharField(blank=True, max_length=500, null=True)),
                ('driver_licence', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, max_length=500, null=True)),
                ('confirmation', models.CharField(blank=True, max_length=500, null=True)),
                ('how_did_you_find', models.CharField(blank=True, max_length=500, null=True)),
                ('recommendations', models.CharField(blank=True, max_length=500, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.UploadCv')),
            ],
        ),
    ]
