# Generated by Django 2.2.2 on 2021-08-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_auto_20210824_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationinfomodel',
            name='UploadCv',
        ),
        migrations.RemoveField(
            model_name='extraeducationinfomodel',
            name='cv',
        ),
    ]
