# Generated by Django 2.2.2 on 2021-08-24 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_auto_20210824_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationinfomodel',
            name='upploadcv',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hr.UploadCv'),
            preserve_default=False,
        ),
    ]
