# Generated by Django 2.2.2 on 2021-08-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_extraeducationinfomodel_upploadcv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationinfomodel',
            options={'verbose_name': "Ma'lumoti", 'verbose_name_plural': "Ma'lumoti"},
        ),
        migrations.AlterModelOptions(
            name='uploadcv',
            options={'verbose_name': 'Ma’lumoti', 'verbose_name_plural': 'Ma’lumoti'},
        ),
        migrations.AddField(
            model_name='uploadcv',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uploadcv',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uploadcv',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='uploadcv',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uploadcv',
            name='kids',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uploadcv',
            name='marriage_status',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uploadcv',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uploadcv',
            name='phone_number',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='uploadcv',
            name='surname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
