# Generated by Django 2.2.2 on 2021-08-25 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_auto_20210825_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalinformationmodel',
            options={'verbose_name': 'Qo‘shimcha ma’lumotlar', 'verbose_name_plural': 'Qo‘shimcha ma’lumotlar'},
        ),
        migrations.AlterModelOptions(
            name='experiencemodel',
            options={'verbose_name': 'Mehnat faoliyati', 'verbose_name_plural': 'Mehnat faoliyati'},
        ),
        migrations.AlterModelOptions(
            name='skillsmodel',
            options={'verbose_name': 'Komputerda ishlash ko‘nikmalari', 'verbose_name_plural': 'Komputerda ishlash ko‘nikmalari'},
        ),
        migrations.AlterField(
            model_name='additionalinformationmodel',
            name='upploadcv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional', to='hr.UploadCv'),
        ),
        migrations.AlterField(
            model_name='educationinfomodel',
            name='upploadcv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='hr.UploadCv'),
        ),
        migrations.AlterField(
            model_name='experiencemodel',
            name='upploadcv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='hr.UploadCv'),
        ),
        migrations.AlterField(
            model_name='extraeducationinfomodel',
            name='upploadcv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraeducation', to='hr.UploadCv'),
        ),
        migrations.AlterField(
            model_name='languagesmodel',
            name='upploadcv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='hr.UploadCv'),
        ),
        migrations.AlterField(
            model_name='skillsmodel',
            name='upploadcv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='hr.UploadCv'),
        ),
    ]
