# Generated by Django 2.2.2 on 2020-12-10 11:20

from django.db import migrations, models
import ungfiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('ungfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typefiles',
            name='ung_file',
            field=models.FileField(blank=True, null=True, upload_to=ungfiles.models.upload_location),
        ),
    ]
