# Generated by Django 2.2.2 on 2020-12-02 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ungfiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='date_updated',
        ),
    ]
