# Generated by Django 2.2.2 on 2020-12-12 05:59

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ungfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='description_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='filename_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='filename_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='filename_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='subcategory_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='subcategory_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='subcategories',
            name='subcategory_uz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
