# Generated by Django 2.2.2 on 2020-12-10 11:23

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ungfiles', '0002_auto_20201210_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='define_sub_category', to='ungfiles.SubCategories')),
            ],
        ),
    ]
