# Generated by Django 2.2.2 on 2020-12-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ungfiles', '0003_allfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typefiles',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='AllFiles',
        ),
        migrations.DeleteModel(
            name='TypeFiles',
        ),
    ]
