# Generated by Django 2.2.2 on 2020-12-10 11:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ungfiles', '0004_auto_20201210_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('date_published', models.DateTimeField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sub_catory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='ungfiles.SubCategories')),
            ],
        ),
    ]
