# Generated by Django 2.2.2 on 2020-12-22 06:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ungfiles', '0004_offcategory_withoutcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='offcategory',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='offcategory',
            name='name_ru',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='offcategory',
            name='name_uz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='withoutcategory',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withoutcategory',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withoutcategory',
            name='description_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withoutcategory',
            name='filename_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withoutcategory',
            name='filename_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withoutcategory',
            name='filename_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
