# Generated by Django 2.2.2 on 2020-12-10 13:31

from django.db import migrations, models
import ungfiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('ungfiles', '0005_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='slug',
        ),
        migrations.AddField(
            model_name='documents',
            name='fileurl_en',
            field=models.FileField(default=1, upload_to=ungfiles.models.upload_location),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents',
            name='fileurl_ru',
            field=models.FileField(default=1, upload_to=ungfiles.models.upload_location),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents',
            name='fileurl_uz',
            field=models.FileField(default=1, upload_to=ungfiles.models.upload_location),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents',
            name='url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
