# Generated by Django 2.2.2 on 2020-12-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ungfiles', '0007_auto_20201210_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='subcategory',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='subcategory_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='subcategory_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='subcategory_uz',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
