# Generated by Django 2.2.2 on 2021-01-19 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ungfiles', '0007_auto_20201228_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documents',
            options={'ordering': ['-date_published']},
        ),
        migrations.AlterModelOptions(
            name='withoutcategory',
            options={'ordering': ['-date_published']},
        ),
    ]
