# Generated by Django 2.2.2 on 2020-12-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ungfiles', '0008_auto_20201211_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
